# spid-smart-button CircleCI configuration

# prepare the cache key used for keeping the node_modules directory across builds
var_2: &cache_key spid-smart-button-{{ .Branch }}-{{ checksum "package.json" }}

# prepare a couple more reusable parameters
var_3: &working_directory /tmp/spid-smart-button
anchor_1: &job_defaults
  working_directory: *working_directory
  docker:
    - image: circleci/node:14.9.0-browsers

# we use a rw SSH key instead of the default one injected by CircleCI because we
#Â use it for deploy as well
anchor_2: &add_ssh_keys
    fingerprints:
      - "29:f1:c5:ce:7d:e8:3a:ac:35:43:d8:b5:e8:f9:f4:9f"

version: 2
jobs:
  # this job builds the production distribution under dist/
  build:
    <<: *job_defaults
    steps:
      - add_ssh_keys: *add_ssh_keys
      - checkout
      - restore_cache:
          key: *cache_key
      - run: sudo npm install -g npm@latest
      - run: npm install grunt --no-save
      - run: npm install --no-save
      - run: npm run build-prod
      - save_cache:
          key: *cache_key
          paths:
            - "node_modules"
      # this preserves things across jobs in this workflow
      - persist_to_workspace:
          root: *working_directory
          paths:
            - "dist/"
            - ".circleci/"
  
  # this job runs the test suite with a headless browser
  test:
    <<: *job_defaults
    steps:
      - add_ssh_keys: *add_ssh_keys
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: *working_directory
      # run the webserver in background, wait a few seconds for it to launch and then run tests
      - run:
          command: npm run serve
          background: true
      - run: sleep 5
      - run: npm test

  # deploy to gh-pages for testing purposes only until we can serve it
  # through the official CDN
  deploy:
    <<: *job_defaults
    steps:
      - add_ssh_keys: *add_ssh_keys
      - attach_workspace:
          at: *working_directory
      - checkout:
          path: /tmp/gh-pages
      - deploy:
          name: Deploy
          command: |
            git config --global user.email no-reply@spid.gov.it
            git config --global user.name "SPID Deploy Bot"

            cd /tmp/gh-pages
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .

            cp -a /tmp/spid-smart-button/dist/. .
            # copy .circleci as well so that the branch filter is honored
            mkdir -p .circleci && cp -a /tmp/spid-smart-button/.circleci/. .circleci/.

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin gh-pages

workflows:
  version: 2
  default_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test

